CREATE DATABASE piscineds;

\c piscineds

CREATE USER jegoh WITH PASSWORD 'mysecretpassword';

GRANT ALL PRIVILEGES ON DATABASE piscineds TO jegoh;

GRANT USAGE ON SCHEMA public TO jegoh;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO jegoh;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO jegoh;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jegoh;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO jegoh;
